spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/esquema_pagos
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect